compatibility_date = "2024-09-02"
main = "build/worker/shim.mjs"
name = "rust-relay"

[build]
command = "cargo install worker-build && worker-build --release"
# command = "cargo install -q worker-build && worker-build --release"
